[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ['ds-test/=lib/ds-test/src/','@openzeppelin/openzeppelin-contracts/=lib/contracts','@openzeppelin/openzeppelin-upgrades/=lib/packages']

# See more config options https://github.com/gakonst/foundry/tree/master/config